# Generated by Django 4.2.7 on 2025-06-26 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customers", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerdocument",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_customer_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
