# Generated by Django 4.2.7 on 2025-07-22 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customerdocument_verified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, help_text='Complete address from Excel import'),
        ),
        migrations.AddField(
            model_name='customer',
            name='communication_preferences',
            field=models.CharField(blank=True, help_text='Communication preferences from Excel', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(db_index=True, default='CUS2025000', help_text='Auto-generated customer code like CUS2025001', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='kyc_documents',
            field=models.CharField(blank=True, help_text='KYC documents list from Excel', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='kyc_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', help_text='KYC verification status from Excel', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_code'], name='customers_c_custome_116ac0_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['kyc_status'], name='customers_c_kyc_sta_76f451_idx'),
        ),
    ]
