# Generated by Django 4.2.7 on 2025-07-22 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_address_customer_communication_preferences_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='customers_c_custome_ec5e63_idx',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_id',
        ),
    ]
