# Generated by Django 4.2.7 on 2025-07-24 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_auto_20250723_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
    ]
