# Generated by Django 4.2.7 on 2025-07-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_remove_address_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile',
            field=models.CharField(choices=[('Normal', 'Normal'), ('HNI', 'HNI (High Net-Worth Individual)')], db_index=True, default='Normal', help_text='Customer profile based on policy count', max_length=10),
        ),
    ]
