# Generated by Django 4.2.7 on 2025-08-11 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uploads', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id_proof', 'ID Proof'), ('address_proof', 'Address Proof'), ('income_proof', 'Income Proof'), ('business_registration', 'Business Registration'), ('tax_document', 'Tax Document'), ('bank_statement', 'Bank Statement'), ('medical_report', 'Medical Report'), ('photo', 'Photograph'), ('signature', 'Signature'), ('authorization', 'Authorization Letter'), ('passport', 'Passport'), ('driving_license', 'Driving License'), ('voter_id', 'Voter ID'), ('pan_card', 'PAN Card'), ('aadhar_card', 'Aadhar Card'), ('utility_bill', 'Utility Bill'), ('rental_agreement', 'Rental Agreement'), ('property_document', 'Property Document'), ('salary_slip', 'Salary Slip'), ('form_16', 'Form 16'), ('itr', 'Income Tax Return'), ('other', 'Other')], db_index=True, help_text='Type of document', max_length=30)),
                ('document_number', models.CharField(blank=True, help_text='Document number (e.g., passport number, license number)', max_length=100)),
                ('is_verified', models.BooleanField(db_index=True, default=False, help_text='Whether the document has been verified')),
                ('verified_at', models.DateTimeField(blank=True, help_text='Timestamp when document was verified', null=True)),
                ('verification_notes', models.TextField(blank=True, help_text='Notes from verification process')),
                ('issue_date', models.DateField(blank=True, help_text='Date when document was issued', null=True)),
                ('expiry_date', models.DateField(blank=True, db_index=True, help_text='Date when document expires', null=True)),
                ('issuing_authority', models.CharField(blank=True, help_text='Authority that issued the document', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the document')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_documents_new_created_objects', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Customer this document belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='documents_new', to='customers.customer')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_documents_new_deleted_objects', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(help_text='Uploaded file for this document', on_delete=django.db.models.deletion.CASCADE, related_name='customer_documents_new', to='uploads.fileupload')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_documents_new_updated_objects', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, help_text='User who verified this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_customer_documents_new', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customers_documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', 'document_type'], name='customers_d_custome_58cd02_idx'), models.Index(fields=['document_type', 'is_verified'], name='customers_d_documen_448b39_idx'), models.Index(fields=['is_verified'], name='customers_d_is_veri_bd691d_idx'), models.Index(fields=['expiry_date'], name='customers_d_expiry__226bc3_idx'), models.Index(fields=['verified_at'], name='customers_d_verifie_85b0cc_idx'), models.Index(fields=['customer', 'is_verified'], name='customers_d_custome_e5109d_idx')],
            },
        ),
    ]
