# Generated by Django 4.2.7 on 2025-08-11 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers_files', '0001_initial'),
        ('customers_documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdocument',
            name='file',
            field=models.ForeignKey(help_text='Customer file for this document', on_delete=django.db.models.deletion.CASCADE, related_name='customer_documents_new', to='customers_files.customerfile'),
        ),
    ]
