# Generated by Django 4.2.7 on 2025-07-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignrecipient',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
