# Generated by Django 4.2.7 on 2025-09-07 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communication_provider', '0003_alter_communicationprovider_channel'),
        ('campaigns', '0003_alter_campaign_target_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='communication_provider',
            field=models.ForeignKey(blank=True, help_text='Communication provider for this campaign', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='communication_provider.communicationprovider'),
        ),
    ]
