# Generated by Django 4.2.7 on 2025-09-07 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_campaign_advanced_scheduling_config_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CampaignScheduleInterval',
        ),
    ]
