# Generated by Django 4.2.7 on 2025-09-07 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '__first__'),
        ('communication_provider', '0003_alter_communicationprovider_channel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '0006_delete_campaign_schedule_intervals'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignScheduleInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sequence_order', models.PositiveIntegerField(default=1, help_text='Order of this interval in the sequence (1, 2, 3, etc.)')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('phone', 'Phone Call'), ('push', 'Push Notification')], help_text='Communication channel for this interval', max_length=20)),
                ('delay_value', models.PositiveIntegerField(default=1, help_text='Delay value (number)')),
                ('delay_unit', models.CharField(choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks')], default='days', help_text='Delay unit (minutes, hours, days, weeks)', max_length=10)),
                ('trigger_conditions', models.JSONField(default=list, help_text='List of trigger conditions for this interval')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this schedule interval is active')),
                ('is_sent', models.BooleanField(default=False, help_text='Whether this interval has been sent')),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='When this interval is scheduled to be sent', null=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When this interval was actually sent', null=True)),
                ('target_count', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('delivered_count', models.PositiveIntegerField(default=0)),
                ('opened_count', models.PositiveIntegerField(default=0)),
                ('clicked_count', models.PositiveIntegerField(default=0)),
                ('campaign', models.ForeignKey(help_text='Campaign this schedule interval belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='schedule_intervals', to='campaigns.campaign')),
                ('communication_provider', models.ForeignKey(blank=True, help_text='Communication provider for this interval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_schedules', to='communication_provider.communicationprovider')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_objects', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_objects', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, help_text='Template to use for this interval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_schedules', to='templates.template')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'campaign_schedule_intervals',
                'ordering': ['campaign', 'sequence_order'],
                'indexes': [models.Index(fields=['campaign', 'sequence_order'], name='campaign_sc_campaig_074f0c_idx'), models.Index(fields=['scheduled_at'], name='campaign_sc_schedul_433a6f_idx'), models.Index(fields=['is_active', 'is_sent'], name='campaign_sc_is_acti_f3f528_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='campaignscheduleinterval',
            constraint=models.UniqueConstraint(fields=('campaign', 'sequence_order'), name='unique_campaign_sequence_order'),
        ),
    ]
