# Generated by Django 4.2.7 on 2025-09-07 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_create_campaign_schedule_intervals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignscheduleinterval',
            name='clicked_count',
        ),
        migrations.RemoveField(
            model_name='campaignscheduleinterval',
            name='delivered_count',
        ),
        migrations.RemoveField(
            model_name='campaignscheduleinterval',
            name='opened_count',
        ),
        migrations.RemoveField(
            model_name='campaignscheduleinterval',
            name='sent_count',
        ),
        migrations.RemoveField(
            model_name='campaignscheduleinterval',
            name='target_count',
        ),
    ]
