# Generated by Django 4.2.7 on 2025-09-22 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_clear_communication_provider_references'),
        ('email_provider', '0004_migrate_communication_providers_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='communication_provider',
            field=models.ForeignKey(blank=True, help_text='Communication provider for this campaign', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='email_provider.emailproviderconfig'),
        ),
        migrations.AlterField(
            model_name='campaignscheduleinterval',
            name='communication_provider',
            field=models.ForeignKey(blank=True, help_text='Communication provider for this interval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_schedules', to='email_provider.emailproviderconfig'),
        ),
    ]
