# Generated by Django 4.2.7 on 2025-09-22 05:21

from django.db import migrations


def migrate_campaigns_to_email_provider(apps, schema_editor):
    """Update campaign foreign keys to reference email_provider_configs"""
    Campaign = apps.get_model('campaigns', 'Campaign')
    CampaignScheduleInterval = apps.get_model('campaigns', 'CampaignScheduleInterval')
    EmailProviderConfig = apps.get_model('email_provider', 'EmailProviderConfig')
    
    # First, set all communication_provider_id to null to avoid foreign key constraint issues
    Campaign.objects.filter(communication_provider_id__isnull=False).update(communication_provider_id=None)
    CampaignScheduleInterval.objects.filter(communication_provider_id__isnull=False).update(communication_provider_id=None)
    
    print("Set all communication_provider_id to null to avoid constraint issues")


def reverse_migrate_campaigns_to_email_provider(apps, schema_editor):
    """Reverse migration - this is not easily reversible"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_update_communication_provider_to_email_provider'),
        ('email_provider', '0004_migrate_communication_providers_data'),
    ]

    operations = [
        migrations.RunPython(
            migrate_campaigns_to_email_provider,
            reverse_migrate_campaigns_to_email_provider
        ),
    ]
