# Generated by Django 4.2.7 on 2025-09-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_migrate_campaigns_to_email_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='current_status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused')], default='active', help_text='Current status for frontend toggle (active/paused)', max_length=20),
        ),
    ]
