# Generated by Django 4.2.7 on 2025-09-22 05:22

from django.db import migrations


def clear_communication_provider_references(apps, schema_editor):
    """Clear all communication_provider_id references to avoid foreign key constraint issues"""
    Campaign = apps.get_model('campaigns', 'Campaign')
    CampaignScheduleInterval = apps.get_model('campaigns', 'CampaignScheduleInterval')
    
    # Set all communication_provider_id to null
    Campaign.objects.filter(communication_provider_id__isnull=False).update(communication_provider_id=None)
    CampaignScheduleInterval.objects.filter(communication_provider_id__isnull=False).update(communication_provider_id=None)
    
    print("Cleared all communication_provider_id references")


def reverse_clear_communication_provider_references(apps, schema_editor):
    """Reverse migration - this is not easily reversible"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_alter_campaign_status'),
    ]

    operations = [
        migrations.RunPython(
            clear_communication_provider_references,
            reverse_clear_communication_provider_references
        ),
    ]
