# Generated by Django 4.2.7 on 2025-09-30 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_campaign_current_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='current_status',
        ),
    ]
