# Generated by Django 4.2.7 on 2025-09-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0013_remove_campaign_current_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignrecipient',
            name='provider_message_id',
            field=models.CharField(blank=True, help_text='Message ID from email provider (SendGrid, SES, etc.)', max_length=255, null=True),
        ),
    ]
