# Generated by Django 4.2.7 on 2025-09-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE templates SET template_type = 'html' WHERE template_type IS NULL;",
            reverse_sql="UPDATE templates SET template_type = NULL WHERE template_type = 'html';"
        ),
        migrations.RunSQL(
            "ALTER TABLE templates ALTER COLUMN template_type SET DEFAULT 'html';",
            reverse_sql="ALTER TABLE templates ALTER COLUMN template_type DROP DEFAULT;"
        ),
    ]
