# Generated by Django 4.2.7 on 2025-08-02 12:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HierarchyManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('unit_name', models.CharField(db_index=True, max_length=200)),
                ('unit_type', models.CharField(choices=[('department', 'Department'), ('region', 'Region'), ('state', 'State'), ('branch', 'Branch'), ('team', 'Team')], db_index=True, default='department', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('manager_id', models.CharField(help_text='Manager ID in format mgr-XXX (e.g., mgr-002)', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^mgr-\\d{3}$', 'Manager ID must be in format mgr-XXX')])),
                ('budget', models.DecimalField(blank=True, decimal_places=2, help_text='Budget allocated to this unit', max_digits=15, null=True)),
                ('target_cases', models.PositiveIntegerField(default=0, help_text='Target number of cases for this unit')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('restructuring', 'Restructuring')], db_index=True, default='active', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_objects', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_objects', to=settings.AUTH_USER_MODEL)),
                ('parent_unit', models.ForeignKey(blank=True, help_text='Parent unit in the hierarchy. Leave blank for root level units.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_units', to='hierarchy.hierarchymanagement')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hierarchy Management',
                'verbose_name_plural': 'Hierarchy Management',
                'db_table': 'hierarchy_management',
                'ordering': ['unit_type', 'unit_name'],
                'indexes': [models.Index(fields=['unit_type', 'status'], name='hierarchy_m_unit_ty_b88b22_idx'), models.Index(fields=['parent_unit', 'unit_type'], name='hierarchy_m_parent__9ccd30_idx'), models.Index(fields=['manager_id'], name='hierarchy_m_manager_edb41d_idx'), models.Index(fields=['status'], name='hierarchy_m_status_b3824e_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='hierarchymanagement',
            constraint=models.UniqueConstraint(fields=('unit_name', 'unit_type', 'parent_unit'), name='unique_unit_in_parent'),
        ),
    ]
