# Generated by Django 4.2.7 on 2025-08-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='hierarchymanagement',
            new_name='hierarchy_m_parent__9206de_idx',
            old_name='hierarchy_m_parent__9ccd30_idx',
        ),
        migrations.AlterField(
            model_name='hierarchymanagement',
            name='parent_unit',
            field=models.CharField(choices=[('none', 'None (Root Level)'), ('north_region', 'North Region (region)'), ('delhi_state', 'Delhi State (state)'), ('connaught_place_branch', 'Connaught Place Branch (branch)'), ('renewals_department', 'Renewals Department (department)'), ('senior_renewal_team', 'Senior Renewal Team (team)')], default='none', help_text="Parent unit in the hierarchy. Select 'None' for root level units.", max_length=50),
        ),
    ]
