# Generated by Django 4.2.7 on 2025-07-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0003_alter_renewalcase_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewalcase',
            name='channel',
            field=models.CharField(choices=[('Online', 'Online'), ('Telecalling', 'Telecalling'), ('Partner', 'Partner'), ('Call Center', 'Call Center'), ('Branch', 'Branch'), ('Walk-in', 'Walk-in'), ('Referral', 'Referral')], default='Online', help_text='Primary channel through which this renewal case was initiated', max_length=50),
        ),
        migrations.AddField(
            model_name='renewalcase',
            name='channel_source',
            field=models.CharField(choices=[('Website', 'Website'), ('Mobile App', 'Mobile App'), ('Outbound', 'Outbound'), ('Inbound', 'Inbound'), ('Bank Channel', 'Bank Channel'), ('Travel Agent', 'Travel Agent'), ('Corporate Broker', 'Corporate Broker'), ('Direct Visit', 'Direct Visit'), ('Phone Call', 'Phone Call')], default='Website', help_text='Specific source within the channel', max_length=100),
        ),
        migrations.AddIndex(
            model_name='renewalcase',
            index=models.Index(fields=['status'], name='renewal_cas_status_5be8c4_idx'),
        ),
        migrations.AddIndex(
            model_name='renewalcase',
            index=models.Index(fields=['priority'], name='renewal_cas_priorit_182f8d_idx'),
        ),
        migrations.AddIndex(
            model_name='renewalcase',
            index=models.Index(fields=['assigned_to'], name='renewal_cas_assigne_6cb989_idx'),
        ),
        migrations.AddIndex(
            model_name='renewalcase',
            index=models.Index(fields=['channel'], name='renewal_cas_channel_0e60eb_idx'),
        ),
        migrations.AddIndex(
            model_name='renewalcase',
            index=models.Index(fields=['channel_source'], name='renewal_cas_channel_2b45c7_idx'),
        ),
    ]
