# Generated by Django 4.2.7 on 2025-07-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0004_renewalcase_channel_renewalcase_channel_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewalcase',
            name='batch_code',
            field=models.CharField(default='BATCH-LEGACY', help_text='Batch code for tracking Excel import batches (e.g., BATCH-2025-07-25-A)', max_length=50),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='renewalcase',
            index=models.Index(fields=['batch_code'], name='renewal_cas_batch_c_5c9465_idx'),
        ),
    ]
