# Generated by Django 4.2.7 on 2025-07-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0005_renewalcase_batch_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renewalcase',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('due', 'Due'), ('overdue', 'Overdue'), ('not_required', 'Not Required')], default='pending', max_length=20),
        ),
    ]
