# Generated by Django 4.2.7 on 2025-07-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0006_add_new_renewal_status_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renewalcase',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('due', 'Due'), ('overdue', 'Overdue'), ('not_required', 'Not Required'), ('assigned', 'Assigned'), ('failed', 'Failed'), ('uploaded', 'Uploaded')], default='pending', max_length=20),
        ),
    ]
