# Generated by Django 4.2.7 on 2025-09-06 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Provider name e.g., 'SendGrid Primary', 'Meta Business API'", max_length=255)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], help_text='Communication channel type', max_length=50)),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default provider for this channel')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this provider is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this provider was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this provider was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When this provider was soft deleted', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this provider', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_communication_providers', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this provider', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_communication_providers', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this provider', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_communication_providers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'communication_providers',
                'ordering': ['channel', 'name'],
                'indexes': [models.Index(fields=['channel'], name='communicati_channel_be715f_idx'), models.Index(fields=['is_active'], name='communicati_is_acti_def823_idx'), models.Index(fields=['is_default'], name='communicati_is_defa_1e3918_idx'), models.Index(fields=['created_at'], name='communicati_created_e69f4f_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='communicationprovider',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('channel', 'is_default'), name='unique_default_per_channel'),
        ),
    ]
