# Generated by Django 4.2.7 on 2025-09-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication_provider', '0002_communicationprovider_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationprovider',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('call', 'Call')], help_text='Communication channel type', max_length=50),
        ),
    ]
