# Generated by Django 4.2.7 on 2025-07-15 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fileupload',
            table='uploads_fileupload',
        ),
    ]
