# Generated by Django 4.2.7 on 2025-07-16 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_alter_fileupload_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fileprocessingqueue',
            table='uploads_fileprocessingqueue',
        ),
        migrations.AlterModelTable(
            name='fileshare',
            table='uploads_fileshare',
        ),
        migrations.AlterModelTable(
            name='imagevariant',
            table='uploads_imagevariant',
        ),
        migrations.AlterModelTable(
            name='uploadsession',
            table='uploads_uploadsession',
        ),
    ]
