# Generated by Django 5.2.6 on 2025-09-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_inbox', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailinboxmessage',
            name='to_email',
        ),
        migrations.AddField(
            model_name='emailinboxmessage',
            name='to_emails',
            field=models.JSONField(blank=True, default=list, help_text='List of recipient email addresses'),
        ),
    ]
