# Generated by Django 4.2.7 on 2025-09-19 10:15

from django.db import migrations, connection


def fix_schema_mismatch(apps, schema_editor):
    """
    Fix the schema mismatch between Django model and database.
    The database already has 'to_emails' but Django thinks it has 'to_email'.
    """
    with connection.cursor() as cursor:
        # Check if to_email column exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'email_inbox_messages' 
            AND column_name = 'to_email'
        """)
        to_email_exists = cursor.fetchone() is not None
        
        # Check if to_emails column exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'email_inbox_messages' 
            AND column_name = 'to_emails'
        """)
        to_emails_exists = cursor.fetchone() is not None
        
        if to_email_exists and not to_emails_exists:
            # Database has to_email, need to rename to to_emails
            cursor.execute("""
                ALTER TABLE email_inbox_messages 
                RENAME COLUMN to_email TO to_emails
            """)
            # Change column type to JSONB
            cursor.execute("""
                ALTER TABLE email_inbox_messages 
                ALTER COLUMN to_emails TYPE JSONB USING to_emails::JSONB
            """)
        elif not to_email_exists and to_emails_exists:
            # Database already has to_emails, nothing to do
            pass
        elif not to_email_exists and not to_emails_exists:
            # Neither exists, create to_emails
            cursor.execute("""
                ALTER TABLE email_inbox_messages 
                ADD COLUMN to_emails JSONB DEFAULT '[]'::JSONB
            """)


def reverse_fix_schema_mismatch(apps, schema_editor):
    """
    Reverse the schema fix if needed.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('email_inbox', '0002_remove_emailinboxmessage_to_email_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_schema_mismatch, reverse_fix_schema_mismatch),
    ]
