# Generated by Django 5.2.6 on 2025-09-20 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_inbox', '0003_auto_20250919_1545'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='emailinboxmessage',
            name='email_inbox_assigne_1569ac_idx',
        ),
        migrations.RenameField(
            model_name='emailinboxmessage',
            old_name='is_processed',
            new_name='is_phishing',
        ),
        migrations.RemoveField(
            model_name='emailinboxmessage',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='emailinboxmessage',
            name='forwarded_at',
        ),
        migrations.RemoveField(
            model_name='emailinboxmessage',
            name='parent_message',
        ),
        migrations.RemoveField(
            model_name='emailinboxmessage',
            name='processing_notes',
        ),
        migrations.RemoveField(
            model_name='emailinboxmessage',
            name='raw_body',
        ),
        migrations.RemoveField(
            model_name='emailinboxmessage',
            name='raw_headers',
        ),
        migrations.AddField(
            model_name='emailinboxmessage',
            name='attachment_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailinboxmessage',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='emailinboxmessage',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='emailinboxmessage',
            name='headers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='emailinboxmessage',
            name='in_reply_to',
            field=models.CharField(blank=True, help_text='In-Reply-To header', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailinboxmessage',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailinboxmessage',
            name='references',
            field=models.CharField(blank=True, help_text='References header', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='emailinboxmessage',
            name='size_bytes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailinboxmessage',
            name='source',
            field=models.CharField(default='webhook', max_length=50),
        ),
        migrations.AddField(
            model_name='emailinboxmessage',
            name='source_message_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailinboxmessage',
            name='subcategory',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='emailattachment',
            name='email_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_attachments', to='email_inbox.emailinboxmessage'),
        ),
        migrations.AlterField(
            model_name='emailinboxmessage',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
