# Generated by Django 4.2.7 on 2025-07-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_upload', '0005_fileupload_deleted_at_fileupload_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='error_details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
