# Generated by Django 4.2.7 on 2025-07-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_upload', '0006_alter_fileupload_error_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file_type',
            field=models.CharField(max_length=100),
        ),
    ]
