# Generated by Django 4.2.7 on 2025-07-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policytype',
            name='category',
            field=models.CharField(choices=[('Motor', 'Motor'), ('Life', 'Life'), ('Property', 'Property'), ('Health', 'Health'), ('Travel', 'Travel')], db_index=True, default='Motor', help_text='Insurance category based on policy type', max_length=20),
        ),
    ]
