# Generated by Django 4.2.7 on 2025-07-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_policytype_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='renewal_date',
            field=models.DateField(blank=True, help_text='Auto-calculated renewal date', null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='renewal_reminder_days',
            field=models.IntegerField(default=30, help_text='Days before end_date to start renewal process'),
        ),
    ]
