# Generated by Django 4.2.7 on 2025-07-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0003_policy_renewal_date_policy_renewal_reminder_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='renewal_reminder_days',
        ),
        migrations.AddField(
            model_name='policy',
            name='grace_period_days',
            field=models.IntegerField(default=30, help_text='Grace period days after policy expiry'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending'), ('suspended', 'Suspended'), ('expiring_soon', 'Expiring Soon')], default='pending', max_length=20),
        ),
    ]
