# Generated by Django 4.2.7 on 2025-07-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0004_add_expiring_soon_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending'), ('suspended', 'Suspended'), ('expiring_soon', 'Expiring Soon'), ('pre_due', 'Pre Due'), ('reinstatement', 'Reinstatement'), ('policy_due', 'Policy Due')], default='pending', max_length=20),
        ),
    ]
