# Generated by Django 4.2.7 on 2025-07-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0006_fix_policy_status_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='renewal_reminder_days',
            field=models.IntegerField(default=30, help_text='Days before end_date to start renewal process (15, 30, 45, 60)'),
        ),
    ]
