# Generated by Django 4.2.7 on 2025-07-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0007_add_renewal_reminder_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='coverage_details',
            field=models.JSONField(default=dict, help_text='Policy-specific coverage details that override or extend policy type defaults'),
        ),
    ]
