# Generated by Django 5.2.6 on 2025-09-16 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_provider', '0001_initial'),
    ]


    operations = [
        migrations.RemoveField(
            model_name='emailproviderconfig',
            name='smtp_host',
        ),
        migrations.RemoveField(
            model_name='emailproviderconfig',
            name='smtp_password',
        ),
        migrations.RemoveField(
            model_name='emailproviderconfig',
            name='smtp_port',
        ),
        migrations.RemoveField(
            model_name='emailproviderconfig',
            name='smtp_use_ssl',
        ),
        migrations.RemoveField(
            model_name='emailproviderconfig',
            name='smtp_use_tls',
        ),
        migrations.RemoveField(
            model_name='emailproviderconfig',
            name='smtp_username',
        ),
    ]
