# Generated by Django 4.2.7 on 2025-09-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_provider', '0002_add_access_key_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailproviderconfig',
            name='communication_provider_id',
            field=models.UUIDField(blank=True, help_text='Temporary field to map from communication_providers table', null=True),
        ),
    ]
