# Generated by Django 5.2.6 on 2025-09-16 10:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_provider', '0003_remove_emailproviderconfig_smtp_host_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailproviderconfig',
            name='access_key',
        ),
        migrations.RemoveField(
            model_name='emailproviderconfig',
            name='health_check_interval',
        ),
        migrations.RemoveField(
            model_name='emailproviderconfig',
            name='last_reset_date',
        ),
        migrations.RemoveField(
            model_name='emailproviderconfig',
            name='secret_key',
        ),
        migrations.AddField(
            model_name='emailproviderconfig',
            name='access_key_id',
            field=models.CharField(blank=True, help_text='AWS Access Key ID (encrypted)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailproviderconfig',
            name='last_reset_daily',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='emailproviderconfig',
            name='last_reset_monthly',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='emailproviderconfig',
            name='secret_access_key',
            field=models.CharField(blank=True, help_text='AWS Secret Access Key (encrypted)', max_length=255, null=True),
        ),
    ]
