# Generated by Django 5.2.6 on 2025-09-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_provider', '0004_remove_emailproviderconfig_access_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailprovidertestresult',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
