# Generated by Django 4.2.7 on 2025-09-22 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_provider', '0004_migrate_communication_providers_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailproviderconfig',
            name='communication_provider_id',
        ),
    ]
