# Generated by Django 4.2.7 on 2025-09-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_provider', '0005_remove_communication_provider_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailproviderconfig',
            name='aws_region',
            field=models.CharField(blank=True, help_text='AWS region for SES', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='emailproviderconfig',
            name='domain',
            field=models.CharField(blank=True, help_text='Mailgun domain', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailproviderconfig',
            name='smtp_host',
            field=models.CharField(blank=True, help_text='SMTP server host', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailproviderconfig',
            name='smtp_password',
            field=models.CharField(blank=True, help_text='SMTP password (encrypted)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailproviderconfig',
            name='smtp_port',
            field=models.PositiveIntegerField(blank=True, help_text='SMTP server port', null=True),
        ),
        migrations.AddField(
            model_name='emailproviderconfig',
            name='smtp_username',
            field=models.CharField(blank=True, help_text='SMTP username (encrypted)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='emailproviderconfig',
            name='provider_type',
            field=models.CharField(choices=[('sendgrid', 'SendGrid'), ('aws_ses', 'AWS SES'), ('mailgun', 'Mailgun'), ('smtp', 'Custom SMTP')], max_length=20),
        ),
    ]
