# Generated by Django 4.2.7 on 2025-10-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_provider', '0006_add_provider_specific_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailproviderconfig',
            name='smtp_use_ssl',
            field=models.BooleanField(default=False, help_text='Use SSL for SMTP connection'),
        ),
        migrations.AddField(
            model_name='emailproviderconfig',
            name='smtp_use_tls',
            field=models.BooleanField(default=False, help_text='Use TLS for SMTP connection'),
        ),
    ]
