# Generated by Django 5.2.6 on 2025-10-07 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('email_provider', '0008_fix_health_log_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailproviderhealthlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailproviderhealthlog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_health_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailproviderhealthlog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailproviderhealthlog',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_health_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailproviderhealthlog',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailproviderhealthlog',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='emailproviderhealthlog',
            name='test_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='emailproviderhealthlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='emailproviderhealthlog',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_health_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emailproviderhealthlog',
            name='response_time',
            field=models.FloatField(default=0.0, help_text='Response time in seconds'),
        ),
    ]
