# Generated by Django 5.2.6 on 2025-10-07 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_provider', '0009_add_missing_test_email_column'),
        ('email_provider', '0009_emailproviderhealthlog_created_at_and_more'),
    ]

    operations = [
    ]
