# Generated by Django 4.2.7 on 2025-10-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_provider', '0010_auto_20251008_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailproviderhealthlog',
            name='response_time',
            field=models.FloatField(default=0.0, help_text='Response time in seconds'),
        ),
    ]
